database:
  host: localhost
  port: 5432
  database: onsori_analysis
  username: postgres

ollama:
  base_url: http://localhost:11434
  model: gemma
  timeout: 30

batch:
  schedule:
    hour: 0
    minute: 0
  timezone: Asia/Seoul

logging:
  level: INFO
  file: logs/app.log
  max_file_size: 10MB
  backup_count: 5
  rotation: daily

api:
  host: 0.0.0.0
  port: 8000
  debug: false

paths:
  static: static
  templates: templates